### ISSUE TITLE
PID script

### ISSUE THREAD

**Issue by alee-cc** [tolland/monit-shared#1]
Can you please share your wrapper script for a process without a pid for Chef server?

**Comment by tolland** [comment]
I was using something like this one;
https://mmonit.com/wiki/Monit/FAQ#pidfile

 ```
#!/bin/bash
 export JAVA_HOME=/usr/local/java/
 CLASSPATH=ajarfile.jar:.

 case $1 in
    start)
       echo $$ > /var/run/xyz.pid;
       exec 2>&1 java -cp ${CLASSPATH} org.something.with.main 1>/tmp/xyz.out 
       ;;
     stop)  
       kill `cat /var/run/xyz.pid` ;;
     *)  
       echo "usage: xyz {start|stop}" ;;
 esac
 exit 0
```

though these days I don't manage any chef-servers, but I would guess it can be configured to write a pid file using systemd, but I've not looked into that

**Comment by alee-cc** [comment]
Thanks for the link. We're still on init.d. Chef doesn't have anything under /var/run/ so it's been difficult to track down a good PID to use.

**Comment by tolland** [comment]
what OS and chef-server version are you running? It looks like the `chef-server-ctl` command can spit out the pid, so you could output that to a file...
https://docs.chef.io/server_services.html#status

Also monit can monitor a process name;
https://mmonit.com/monit/documentation/monit.html#Program

**Comment by alee-cc** [comment]
We're using the AWS AMI, based loosely on CentOS I believe. 

That's a good idea about pulling the PID out of chef-server-ctl status. Thank you!
